#!/usr/bin/env ruby

require 'require_all'
require_rel 'lib'

OPEN_WEATHER_MAP_APP_ID = ENV['OPEN_WEATHER_MAP_APP_ID'] || 'YOUR_ID'
GOOGLE_CLOUD_PROJECT_ID = ENV['GOOGLE_CLOUD_PROJECT_ID'] || 'PROJECT_ID'
GOOGLE_CLOUD_CREDENTIALS_PATH = ENV['GOOGLE_CLOUD_CREDENTIALS_PATH'] || 'CREDENTIALS_PATH'

weather = OpenWeatherMapProvider.new(OPEN_WEATHER_MAP_APP_ID)
translate = GoogleTranslateProvider.new(GOOGLE_CLOUD_PROJECT_ID,
                                        GOOGLE_CLOUD_CREDENTIALS_PATH)
cli = WeatherForecast.new(weather, translate)
cli.forecast
